import React from 'react';
import { X, ShieldAlert, AlertTriangle, CheckCircle2 } from 'lucide-react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="relative w-full max-w-lg bg-[#0E1422] border border-slate-700/80 rounded-2xl p-6 sm:p-8 shadow-2xl text-xs space-y-4">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white rounded-full bg-slate-800/80"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center gap-3 pb-3 border-b border-slate-800">
          <div className="w-10 h-10 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center shrink-0">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Responsible Gaming & Statistical Disclaimer</h3>
            <span className="text-[11px] text-slate-400">Predict Mind AI Platform Policy</span>
          </div>
        </div>

        <div className="text-slate-300 space-y-3 leading-relaxed">
          <p>
            <strong>1. No Financial Guarantees:</strong> Predictions generated by Predict Mind AI are derived from mathematical modeling, historical form, head-to-head records, and AI algorithms. <em>Sporting events are unpredictable and no outcome is ever guaranteed.</em>
          </p>
          <p>
            <strong>2. Independent Decision Making:</strong> All predictions, confidence scores, and market probabilities are purely informational and intended to assist your personal analytical research. You are solely responsible for your wagering choices.
          </p>
          <p>
            <strong>3. Strict 18+ Requirement:</strong> Betting services are strictly reserved for individuals aged 18 years or older (or the legal age of majority in your jurisdiction).
          </p>
          <p>
            <strong>4. Bankroll Discipline:</strong> Never stake money you cannot afford to lose. We strongly advocate for disciplined flat unit staking (1% to 2.5% of total bankroll per match) and predefined loss limits.
          </p>
        </div>

        <div className="pt-3 border-t border-slate-800 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold"
          >
            I Understand & Agree
          </button>
        </div>
      </div>
    </div>
  );
};
